logging:
  level:
    ROOT: info
    jp.gmo.user: info
  file:
    path: log

server:
  port: 8081

spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
     type: com.zaxxer.hikari.HikariDataSource
     url: jdbc:mysql://10.1.10.250:3306/db_webinternal?useUnicode=true&characterEncoding=utf8&useSSL=false
     username: runsystem
     password: Admin123
     hikari:
         auto-commit: false
         data-source-properties:
             cachePrepStmts: true
             prepStmtCacheSize: 250
             prepStmtCacheSqlLimit: 2048
             useServerPrepStmts: true
  jpa:
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
     database: MYSQL
     show-sql: true
     mapping-resources:
        sql/account-sql.xml
  jackson:
    serialization:
      write-dates-as-timestamps: false