logging:
  level:
    ROOT: info
    jp.gmo.user: info
  file:
    path: log

spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
     type: com.zaxxer.hikari.HikariDataSource
     url: jdbc:mysql://10.1.10.250:3306/db_gzr_webinternal?useUnicode=true&characterEncoding=utf8&useSSL=false
     username: runsystem
     password: Admin123
     hikari:
         auto-commit: false
         data-source-properties:
             cachePrepStmts: true
             prepStmtCacheSize: 250
             prepStmtCacheSqlLimit: 2048
             useServerPrepStmts: true
  jpa:
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
     database: MYSQL
     show-sql: true
     mapping-resources:

jwt:
  base64-secret: MTIxZGJkMGFlODM1Zjg2MGNmZmYwNTBkNmVmM2Q4MGRlMzk4NjNkOWQyZGJlNjViYTI4NWEzMTg5YWI2ZDYzZjA1MTE3MTg4ZWM2YTAyY2ExYTVjZTYwZTRkYWIyYmUxNTBhZTM2NjBlYTA0OWU0NTY0MmM4OGQ2NjU2ZmFmMGI=
  token-validity: 86400